if (( $+commands[fortune] )); then
  fortune -a
fi

function compile-ssh-config() {
    rm -f ~/.ssh/config
    echo <<EOF
    # --* This file is automatically generated and overwritten by .zlogin. *--
    # --* Put configuration into a file in ~/.ssh/config.d instead. *--
EOF
    cat ~/.ssh/config.d/* >> ~/.ssh/config
}

if (( $+commands[ssh] )) && [[ -d ~/.ssh/config.d/ ]]; then
    compile-ssh-config
fi
