if (( $+commands[fortune] )); then
  fortune -a
fi

function compile-ssh-config() {
    >~/.ssh/config cat <<EOF
# --* This file is automatically generated and overwritten by .zlogin. *--
# --* Put configuration into a file in ~/.ssh/config.d instead. *--
EOF
    for file in ~/.ssh/config.d/*; do
        printf "\n# --- $file ---\n" >> ~/.ssh/config
        cat $file >> ~/.ssh/config
    done
}

if (( $+commands[ssh] )) && [[ -d ~/.ssh/config.d/ ]]; then
    compile-ssh-config
fi
