function compile-ssh-config() {
    >~/.ssh/config cat <<EOF
# --* This file is automatically generated and overwritten by .zlogin. *--
# --* Put configuration into a file in ~/.ssh/config.d instead. *--
EOF
    for file in ~/.ssh/config.d/*; do
        printf "\n# --- $file ---\n" >> ~/.ssh/config
        sed 's;\$(XDG_CACHE_HOME|\{XDG_CACHE_HOME\});'"${XDG_CACHE_HOME};" $file >> ~/.ssh/config
    done
}

function {
    setopt LOCAL_OPTIONS

    (( $+commands[git] )) && printf "Dotfiles updated: $(git --git-dir ~/.dotfiles/.git --work-tree ~/.dotfiles log -1 --format=%cr)\n\n" &|
    (( $+commands[fortune] )) && fortune -a &|
    (( $+commands[ssh] )) && [[ -d ~/.ssh/config.d/ ]] && compile-ssh-config &|
}
