repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: trailing-whitespace
      - id: file-contents-sorter
        files: "^.config/nvim/spellfile.add$"
        args: ["--ignore-case"]
  - repo: https://github.com/woodruffw/zizmor
    rev: v0.1.6
    hooks:
    - id: zizmor
