[bundle]
development = ["bpython[urwid]", "ptpython", "pudb"]

# --- Development ---

[virtualenv.dev]
install-bundle = ["development"]
install = [
    "betterpath",
    "coverage>=5.0a7",
    "filesystems",
    "glom",
    "green",
    "hypothesis",
    "inflect",
    "jinja2",
    "pendulum",
    "pyperf",
    "pyrsistent",
    "pytest",
    "pytest-cov",
    "pytoml",
    "pyyaml",
    "setuptools",
    "testrepository",
    "treq",
    "twisted[conch,tls]",
    "vmprof",
]
link = [
    "bpython",
    "bpython-urwid",
    "conch",
    "coverage>=5.0a7",
    "glom",
    "green",
    "pip",
    "pyperf",
    "python",
    "ptpython",
    "pudb",
    "py.test",
    "testr",
    "trial",
    "twist",
    "twistd",
    "vmprofshow",
]

[virtualenv.dev3]
python = "pypy3"
install-bundle = ["development"]
install = [
    "betterpath",
    "coverage",
    "filesystems",
    "green",
    "hypothesis",
    "inflect",
    "jinja2",
    "pendulum",
    "pyperf",
    "pyrsistent",
    "pytest",
    "pytest-cov",
    "pytoml",
    "pyyaml",
    "setuptools",
    "testrepository",
    "treq",
    "twisted[conch,tls]",
]
link = [
    "bpython:bpython3",
    "bpython-urwid:bpython-urwid3",
    "coverage:coverage3",
    "green:green3",
    "pip:pip3",
    "python:python3",
    "ptpython:ptpython3",
    "pudb3:pudb3",
    "py.test:py.test3",
    "pyperf:pyperf3",
    "testr:testr3",
    "trial:trial3",
    "twist:twist3",
]
link-module = ["pydoc"]

[virtualenv.aws]
python = "python3.7"
install-bundle = ["development"]
install = ["awscli", "boto", "boto3", "saws"]
link = ["aws", "saws"]

[virtualenv.black]
python = "python3.7"
install = ["black"]
link = ["black"]

[virtualenv.colortest]
install = ["colortest"]
link = ["colortest"]

[virtualenv.detect-secrets]
install = ["detect-secrets"]
link = ["detect-secrets"]

[virtualenv.doc8]
install = ["doc8"]
link = ["doc8"]

[virtualenv.google]
install-bundle = ["development"]
install = ["google-api-python-client"]

[virtualenv.hg]
python = "python2"
install = ["mercurial"]
link = ["hg"]

[virtualenv.httpie]
install = ["httpie"]
link = ["http"]

[virtualenv.httpstat]
install = ["httpstat"]
link = ["httpstat"]

[virtualenv.jsonschema]
install-bundle = ["development"]
install = ["jsonschema[format]", "mock", "twisted"]
link = ["jsonschema"]

[virtualenv.litecli]
python = "pypy3"
install = ["litecli"]
link = ["litecli"]

[virtualenv.ml]
python = "python3.7"
install-bundle = ["development"]
install = [
    "numpy",
    "jupyter",
    "jupyterlab",
    "pandas",

    "ipympl",
    "matplotlib",

    "altair",
    "git+https://github.com/altair-viz/altair_pandas",

    "bokeh",
    "graphviz",
    "plotly",
    "plotnine",
    "seaborn",
    "yellowbrick",

    # auto-sklearn looks like it depends on old scikit-learn at the minute.
    # "auto-sklearn",
    "featuretools",
    "h2o",

    "scikit-learn",
    "scikit-optimize[plots]",
    "scikit-plot",

    "tensorflow",
    "torch",
    "xgboost",
    "xgbfir",

    "eli5",
    # Lime looks like it depends on old matplotlib at the minute.
    # "lime",
    "shap",

    "hdrhistogram",
    "networkx",
    "octave_kernel",

    "kaggle",

    "nteract_on_jupyter",

    "hyperlink",
    "pyrsistent",
    "requests",
    "twisted",
]
link = ["jupyter", "kaggle", "ptpython:ml", "xgbfir"]

[virtualenv.lime]
python = "python3.7"
install-bundle = ["development"]
install = [
    "lime",

    "hyperlink",
    "pyrsistent",
    "requests",
    "twisted",
]

[virtualenv.autosklearn]
python = "python3.7"
install-bundle = ["development"]
install = [
    "auto-sklearn",

    "hyperlink",
    "pyrsistent",
    "requests",
    "twisted",
]

[virtualenv.bandit]
python = "pypy3"
install = ["bandit"]
link = ["bandit"]

[virtualenv.check-manifest]
python = "python3.7"
install = ["check-manifest"]
link = ["check-manifest"]

[virtualenv.mkpkg]
install = ["-e", "${DEVELOPMENT}/mkpkg"]
link = ["mkpkg"]

[virtualenv.neovim]
install = ["pynvim"]

[virtualenv.neovim3]
python = "python3"
install = ["pynvim"]

[virtualenv.ngxtop]
install = ["ngxtop"]
link = ["ngxtop"]

[virtualenv.pep517]
python = "pypy3"
install = ["pep517"]
link-module = ["pep517.build:pep517-build", "pep517.check:pep517-check"]

[virtualenv.pex]
install = ["pex"]
link = ["pex"]

[virtualenv.poetry]
install = ["poetry"]
link = ["poetry"]

[virtualenv.piptools]
install = ["pip-tools"]
link = ["pip-compile"]

[virtualenv.piptools3]
python = "pypy3"
install = ["pip-tools"]
link = ["pip-compile:pip-compile3"]

[virtualenv.pychromecast]
python = "python3.7"
install-bundle = ["development"]
install = ["-e", "${DEVELOPMENT}/cast-cli"]
link = ["cast"]

[virtualenv.pydocstyle]
python = "python3.7"
install = ["pydocstyle"]
link = ["pydocstyle"]

[virtualenv.pypinfo]
python = "python3.7"
install = ["pypinfo"]
link = ["pypinfo"]

[virtualenv.salt]
install-bundle = ["development"]
install = ["salt", "salt-ssh"]
link = [
    "salt",
    "salt-api",
    "salt-call",
    "salt-cloud",
    "salt-cp",
    "salt-key",
    "salt-master",
    "salt-minion",
    "salt-proxy",
    "salt-run",
    "salt-ssh",
    "salt-syndic",
    "salt-unity",
]

[virtualenv.shiv]
python = "python3.7"
install = ["shiv"]
link = ["shiv"]

[virtualenv.sphinx]
python = "python3.7"
install-bundle = ["development"]
install = ["sphinx", "sphinxcontrib.spelling"]
link = [
    "rst2html.py",
    "rst2html5.py",
    "sphinx-apidoc",
    "sphinx-autogen",
    "sphinx-build",
    "sphinx-quickstart",
]

[virtualenv.sphobjinv]
python = "pypy3"
install = ["sphobjinv"]
link = ["sphobjinv"]

[virtualenv.style]
install = ["ebb-lint"]
link = ["flake8"]

[virtualenv.style3]
python = "pypy3"
install = ["ebb-lint"]
link = ["flake8:flake83"]

[virtualenv.subunit]
install = ["python-subunit"]
link = [
    "subunit-1to2",
    "subunit-2to1",
    "subunit-filter",
    "subunit-ls",
    "subunit-notify",
    "subunit-output",
    "subunit-stats",
    "subunit-tags",
    "subunit2csv",
    "subunit2disk",
    "subunit2gtk",
    "subunit2junitxml",
    "subunit2pyunit",
    "tap2subunit",
]

[virtualenv.tox]
python = "pypy3"
install = ["tox"]
link = ["tox"]

[virtualenv.twine]
install = ["twine"]
link = ["twine"]

[virtualenv.remarshal]
install = ["remarshal"]
link = [
    "json2json",
    "toml2json",
    "yaml2json",
    "json2toml",
    "toml2toml",
    "yaml2toml",
    "json2yaml",
    "toml2yaml",
    "yaml2yaml",
]

[virtualenv.youtube-dl]
install = ["youtube-dl"]
link = ["youtube-dl"]

[virtualenv.watchdog]
install = ["watchdog"]
link = ["watchmedo"]

# --- Developing ---

[virtualenv.blog]
python = "python3"
install = ["-r", "${DEVELOPMENT}/julian.github.io/requirements.txt"]
link = ["invoke", "pelican", "pelican-quickstart", "pelican-themes"]

[virtualenv.diff]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/diff", "twisted[tls]"]

[virtualenv.filesystems]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/filesystems", "testscenarios", "twisted"]

[virtualenv.great]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/Great", "twisted[tls]"]
requirements = [
    "${DEVELOPMENT}/Great/test-requirements.txt",
    "${DEVELOPMENT}/Great/automanual/requirements.txt",
]

[virtualenv.gtfo]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/gtfo"]
link = ["gtfo"]

[virtualenv.minion]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/Minion", "twisted[tls]"]
requirements = ["${DEVELOPMENT}/Minion/test-requirements.txt"]
