[virtualenv.ca]

[virtualenv.dev]
install = [
    "bpython[urwid]",
    "coverage",
    "detox",
    "git+https://github.com/habnabit/ebb-lint#egg=ebb-lint",
    "filesystems",
    "flake8",
    "hypothesis",
    "ptpython",
    "pudb",
    "pyrsistent",
    "tox",
    "twisted[conch,h2,tls]",
]
link = [
    "bpython",
    "bpython-urwid",
    "coverage",
    "detox",
    "flake8",
    "ptpython",
    "pudb",
    "trial",
    "twist",
]

# [virtualenv.dev3]

[virtualenv.jupyter]
install = ["jupyter", "hdrhistogram", "matplotlib", "numpy", "ptpython", "requests"]
link = ["jupyter-notebook"]

[virtualenv.httpie]
install = ["httpie"]
link = ["http"]

[virtualenv.httpstat]
install = ["httpstat"]
link = ["httpstat"]

[virtualenv.neovim]
install = ["neovim"]

#
# [virtualenv.neovim3]
# install = ["neovim"]

[virtualenv.awscli]
install = ["awscli"]
link = ["aws"]

[virtualenv.mycli]
install = ["mycli"]
link = ["mycli"]

[virtualenv.twine]
install = ["twine"]
link = ["twine"]

[virtualenv.rtb]
requirements = [
    # "/home/julian/Development/Magnetic/rtb/deploy-requirements.txt",
    "/home/julian/Development/Magnetic/rtb/test-requirements.txt",
]
