[virtualenv.dev]
install = [
    "betterpath",
    "bpython[urwid]",
    "coverage",
    "ebb-lint",
    "filesystems",
    "flake8",
    "green",
    "hypothesis",
    "inflect",
    "ptpython",
    "pudb",
    "pyperf",
    "pyrsistent",
    "pytest",
    "pytoml",
    "pyyaml",
    "setuptools",
    "testrepository",
    "treq",
    "twisted[conch,tls]",
    "vmprof",
]
link = [
    "bpython",
    "bpython-urwid",
    "conch",
    "coverage",
    "flake8",
    "green",
    "pip",
    "python",
    "ptpython",
    "pudb",
    "py.test",
    "testr",
    "trial",
    "twist",
    "twistd",
    "vmprofshow",
]

[virtualenv.dev3]
python = "pypy3"
install = [
    "betterpath",
    "bpython[urwid]",
    "coverage",
    "ebb-lint",
    "filesystems",
    "flake8",
    "green",
    "hypothesis",
    "inflect",
    "ptpython",
    "pudb",
    "pyperf",
    "pyrsistent",
    "pytest",
    "pytoml",
    "pyyaml",
    "setuptools",
    "testrepository",
    "treq",
    "twisted[conch,tls]",
]
link = [
    "bpython:bpython3",
    "bpython-urwid:bpython-urwid3",
    "coverage:coverage3",
    "flake8:flake83",
    "green:green3",
    "pip:pip3",
    "python:python3",
    "ptpython:ptpython3",
    "pudb3:pudb3",
    "py.test:py.test3",
    "testr:testr3",
    "trial:trial3",
    "twist:twist3",
]

[virtualenv.aws]
install = [
    "awscli",
    "boto",
    "boto3",
    "ptpython",
    "pudb",
]

[virtualenv.blog]
python = "python3"
install = ["-r", "${DEVELOPMENT}/julian.github.io/requirements.txt"]
link = ["invoke", "pelican", "pelican-quickstart", "pelican-themes"]

[virtualenv.awscli]
install = ["awscli"]
link = ["aws"]

[virtualenv.black]
python = "python3.7"
install = ["black"]
link = ["black"]

[virtualenv.diff]
install = [
    "${DEVELOPMENT}/diff",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]

[virtualenv.filesystems]
install = [
    "${DEVELOPMENT}/filesystems",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "testscenarios",
    "twisted",
]

[virtualenv.google]
install = [
    "google-api-python-client",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]

[virtualenv.great]
install = [
    "-r", "${DEVELOPMENT}/Great/test-requirements.txt",
    "-r", "${DEVELOPMENT}/Great/automanual/requirements.txt",
    "${DEVELOPMENT}/Great",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]

[virtualenv.gtfo]
install = ["${DEVELOPMENT}/gtfo"]
link = ["gtfo"]

[virtualenv.hg]
python = "python2"
install = ["mercurial"]
link = ["hg"]

[virtualenv.httpie]
install = ["httpie"]
link = ["http"]

[virtualenv.httpstat]
install = ["httpstat"]
link = ["httpstat"]

[virtualenv.jsonschema]
install = ["jsonschema[format]", "mock", "ptpython", "pudb", "twisted"]
link = ["jsonschema"]

[virtualenv.litecli]
python = "pypy3"
install = ["litecli"]
link = ["litecli"]

[virtualenv.minion]
install = [
    "${DEVELOPMENT}/Minion",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]
requirements = ["${DEVELOPMENT}/Minion/test-requirements.txt"]

[virtualenv.ml]
python = "python3.7"
install = [
    "numpy",
    "jupyter",
    "jupyterlab",
    "pandas",

    "altair",
    "bokeh",
    "graphviz",
    "matplotlib",
    "plotly",
    "plotnine",
    "scikit-plot",
    "seaborn",
    "yellowbrick",

    "featuretools",
    "h2o",

    "scikit-learn",
    "tensorflow",
    "xgboost",

    "eli5",
    # Lime looks like it depends on old matplotlib at the minute.
    # "lime",
    "shap",

    "hdrhistogram",
    "networkx",
    "octave_kernel",

    "hyperlink",
    "ptpython",
    "pudb",
    "pyrsistent",
    "requests",
    "twisted",
]
link = ["jupyter"]

[virtualenv.lime]
python = "python3.7"
install = ["lime"]

[virtualenv.neovim]
install = ["jedi", "neovim"]

[virtualenv.neovim3]
python = "python3"
install = ["jedi", "neovim"]

[virtualenv.ngxtop]
install = ["ngxtop"]
link = ["ngxtop"]

[virtualenv.pex]
install = ["pex", "requests"]
link = ["pex"]

[virtualenv.shiv]
python = "python3.7"
install = ["shiv"]
link = ["shiv"]

[virtualenv.pipenv]
install = ["pipenv"]
link = ["pew", "pipenv"]

[virtualenv.piptools]
install = ["pip-tools"]
link = ["pip-compile"]

[virtualenv.pychromecast]
install = ["bpython", "cast", "ptpython", "pychromecast"]
link = ["cast"]

[virtualenv.salt]
install = [
    "salt",
    "salt-ssh",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
link = [
    "salt",
    "salt-api",
    "salt-call",
    "salt-cloud",
    "salt-cp",
    "salt-key",
    "salt-master",
    "salt-minion",
    "salt-proxy",
    "salt-run",
    "salt-ssh",
    "salt-syndic",
    "salt-unity",
]

[virtualenv.sphinx]
install = [
    "sphinx",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
link = [
    "rst2html.py",
    "rst2html5.py",
    "sphinx-apidoc",
    "sphinx-autogen",
    "sphinx-build",
    "sphinx-quickstart",
]

[virtualenv.tox]
python = "pypy3"
install = ["tox"]
link = ["tox"]

[virtualenv.twine]
install = ["twine"]
link = ["twine"]

[virtualenv.remarshal]
install = ["remarshal"]
link = [
    "json2json",
    "toml2json",
    "yaml2json",
    "json2toml",
    "toml2toml",
    "yaml2toml",
    "json2yaml",
    "toml2yaml",
    "yaml2yaml",
]

[virtualenv.watchdog]
install = ["watchdog"]
link = ["watchmedo"]
