[virtualenv.dev]
install = [
    "betterpath",
    "bpython[urwid]",
    "coverage",
    "detox",
    "ebb-lint",
    "filesystems",
    "flake8",
    "green",
    "hypothesis",
    "inflect",
    "perf",
    "ptpython",
    "pudb",
    "pyrsistent",
    "pytest",
    "pytoml",
    "pyyaml",
    "setuptools",
    "testrepository",
    "tox",
    "treq",
    "twisted[conch,tls]",
    "vmprof",
]
link = [
    "bpython",
    "bpython-urwid",
    "conch",
    "coverage",
    "detox",
    "flake8",
    "green",
    "pip",
    "python",
    "ptpython",
    "pudb",
    "py.test",
    "testr",
    "tox",
    "trial",
    "twist",
    "twistd",
    "vmprofshow",
]

[virtualenv.dev3]
python = "python3"
install = [
    "betterpath",
    "bpython[urwid]",
    "coverage",
    "detox",
    "ebb-lint",
    "filesystems",
    "flake8",
    "green",
    "hypothesis",
    "inflect",
    "perf",
    "ptpython",
    "pudb",
    "pyrsistent",
    "pytest",
    "pytoml",
    "pyyaml",
    "setuptools",
    "testrepository",
    "tox",
    "treq",
    "twisted[conch,tls]",
    "vmprof",
]

[virtualenv.awscli]
install = ["awscli"]
link = ["aws"]

[virtualenv.diff]
install = [
    "${DEVELOPMENT}/diff",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]

[virtualenv.filesystems]
install = [
    "${DEVELOPMENT}/filesystems",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "testscenarios",
    "twisted",
]

[virtualenv.google]
install = [
    "google-api-python-client",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]

[virtualenv.great]
install = [
    "${DEVELOPMENT}/Great",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]

[virtualenv.gtfo]
install = ["${DEVELOPMENT}/gtfo"]
link = ["gtfo"]

[virtualenv.hg]
install = ["mercurial"]
link = ["hg"]

[virtualenv.httpie]
install = ["httpie"]
link = ["http"]

[virtualenv.httpstat]
install = ["httpstat"]
link = ["httpstat"]

[virtualenv.jsonschema]
install = ["jsonschema[format]", "mock", "ptpython", "pudb", "twisted"]
link = ["jsonschema"]

[virtualenv.jupyter]
install = ["jupyter", "hdrhistogram", "numpy", "ptpython", "requests"]
link = ["jupyter-notebook"]

[virtualenv.minion]
install = [
    "${DEVELOPMENT}/Minion",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]
requirements = ["${DEVELOPMENT}/Minion/test-requirements.txt"]

[virtualenv.mycli]
install = ["mycli"]
link = ["mycli"]

[virtualenv.neovim]
install = ["neovim"]

[virtualenv.ngxtop]
install = ["ngxtop"]
link = ["ngxtop"]

[virtualenv.neovim3]
python = "python3"
install = ["neovim"]

[virtualenv.pex]
install = ["pex"]
link = ["pex"]

[virtualenv.shiv]
python = "python3"
install = ["shiv"]
link = ["shiv"]

[virtualenv.pipenv]
install = ["pipenv"]
link = ["pew", "pipenv"]

[virtualenv.pychromecast]
install = ["bpython", "cast", "ptpython", "pychromecast"]
link = ["cast"]

[virtualenv.sphinx]
install = ["sphinx"]
link = [
    "rst2html.py",
    "rst2html5.py",
    "sphinx-apidoc",
    "sphinx-autogen",
    "sphinx-build",
]

[virtualenv.tqdm]
install = ["tqdm"]
link = ["tqdm"]

[virtualenv.twine]
install = ["twine"]
link = ["twine"]

[virtualenv.yml2json]
install = ["yml2json"]
link = ["yml2json"]

[virtualenv.watchdog]
install = ["watchdog"]
link = ["watchmedo"]
