[bundle]
development = [
    "bpython[urwid]",
    "debugpy",
    "pipdeptree",
    "ptpython",
    "pudb",
    "pytest",
    "q",
    "rich; python_version>='3'",
    "virtue",
]
core = [
    "coverage",
    "filesystems",
    "glom",
    "hyperlink",
    "hypothesis",
    "inflect",
    "jinja2",
    "pathlib2; python_version<='2.7'",
    "subprocess32; python_version<='2.7'",
    "pyinstrument; python_version>='3' and platform_python_implementation != 'PyPy'",
    "pyperf; python_version>='3'",
    "pyrsistent",
    "pytest-cov",
    "python-papi; platform_system=='Linux' and platform_machine != 'aarch64'",
    "pytoml",
    "pyyaml",
    "twisted[conch,tls]; python_version>='3'",
]

# --- Development ---

[virtualenv.dev]
python = "pypy3"
install-bundle = ["core", "development"]
link = [
    "bpython:bpython",
    "bpython-urwid:bpython-urwid",
    "coverage:coverage",
    "glom:glom",
    "pip:pip",
    "ptpython:ptpypy",
    "pudb3:pudb",
    "py.test:py.test",
    "pyperf:pyperf",
    "testr:testr",
    "trial:trial",
    "twist:twist",
]
link-module = ["pydoc"]

[virtualenv.dev-cpython]
install-bundle = ["core", "development"]
install = ["pyinstrument"]
link = [
    "bpython:bpython-cpython3",
    "bpython-urwid:bpython-urwid-cpython3",
    "coverage:coverage-cpython3",
    "glom:glom-cpython3",
    "pip:pip-cpython3",
    "ptpython:ptpython",
    "ptpython:ptpython3",
    "pyinstrument",
    "python:python3",
    "python:cpython3",
    "pudb3:pudb-cpython3",
    "py.test:py.test-cpython3",
    "pyperf:pyperf-cpython3",
    "testr:testr-cpython3",
    "trial:trial-cpython3",
    "twist:twist-cpython3",
]
link-module = ["venv"]

[virtualenv.aubio]
install = ["aubio>=0.4.9"]
link = ["aubio", "aubiocut"]

[virtualenv.bandit]
install = ["bandit"]
link = ["bandit"]

[virtualenv.beets]
install = ["beets", "beautifulsoup4", "pyacoustid", "requests"]
link = ["beet"]

[virtualenv.black]
install = ["black[jupyter]"]
link = ["black"]

[virtualenv.catt]
install = ["catt"]
link = ["catt"]

[virtualenv.cookiecutter]
install = ["cookiecutter"]
link = ["cookiecutter"]

[virtualenv.colortest]
install = ["colortest"]
link = ["colortest"]

[virtualenv.detect-secrets]
install = ["detect-secrets"]
link = ["detect-secrets"]

[virtualenv.doc8]
install = ["doc8", "pygments"]
link = ["doc8"]

[virtualenv.esbonio]
install = ["esbonio"]
link = ["esbonio"]

[virtualenv.findme-cpython3]
install-bundle = ["development"]
install = ["findme"]
link = ["findme:findme-cpython3"]

[virtualenv.findme-pypy3]
python = "pypy3"
install-bundle = ["development"]
install = ["findme"]
link = ["findme:findme-pypy3"]

[virtualenv.flake8]
install = [
    "flake8",
    "flake8-bugbear",
    "flake8-commas",
    "flake8-quotes",
    "flake8-broken-line",
    "yesqa",
]
link = ["flake8", "yesqa"]

[virtualenv.google]
install-bundle = ["development"]
install = [
    "google-api-python-client",
    "google-auth-httplib2",
    "google-auth-oauthlib",
]

[virtualenv.gpt]
install-bundle = ["development"]
install = [
  "chromadb",
  "langchain",
  "llama-cpp-python",
  "pygpt4all",
]

[virtualenv.hg]
install = ["mercurial"]
link = ["hg"]

[virtualenv.httpie]
install = ["httpie"]
link = ["http", "https"]

[virtualenv.httpstat]
install = ["httpstat"]
link = ["httpstat"]

[virtualenv.imaging]
install-bundle = ["development"]
install = [
    "libraw-cffi",
    "pillow",
    "rawkit",
]

[virtualenv.interrogate]
install = ["interrogate"]
link = ["interrogate"]

[virtualenv.isort]
install = ["isort"]
link = ["isort"]

[virtualenv.jsonschema]
install-bundle = ["development"]
install = [
    "check-jsonschema",
    "hypothesis-jsonschema",
    "jsonschema[format]",
    "twisted",
]
link = ["check-jsonschema", "jsonschema"]

[virtualenv.litecli]
install = ["litecli"]
link = ["litecli"]

[virtualenv.math]
install-bundle = ["development"]
install = ["sympy"]
link = ["ptpython:math"]

[virtualenv.maturin]
install = ["maturin"]
link = ["maturin"]

[virtualenv.ml]
python = "python3.11"
post-commands = [
    [
        "jupyter",
        "labextension",
        "install",
        "@jupyter-widgets/jupyterlab-manager",
        "jupyter-matplotlib",
    ],
    ["jupyter", "lab", "build"],
]
install-bundle = ["core", "development"]
install = [
    "numpy>=1.21.1",
    "scipy>=1.7.3",
    "pandas>=1.3.1",

    "numba>=0.57.0rc1",
    "llvmlite>=0.38.0rc1",

    "dask[complete]>=2021.11.2",
    "pyspark>=3.2.0",

    "jupyter",
    "jupyterlab",
    "nbdev",
    "nteract_on_jupyter",
    "octave_kernel",

    "jupyter-lsp",
    "python-language-server[all]>=0.36.2",

    "ipympl>=0.8.1",
    "matplotlib>=3.4.3",
    "altair>=4.0.1",
    "altair-viewer",
    "altair_saver>=0.4.0",
    "git+https://github.com/altair-viz/altair_pandas",

    "bokeh>=2.4.1",
    "graphviz>=0.18.1",
    "plotly>=5.4.0",
    "plotnine>=0.8.0",
    "seaborn>=0.11.2",
    "git+https://github.com/DistrictDataLabs/yellowbrick#egg=yellowbrick",

    "streamlit>=1.2.0",
    "voila>=0.2.16",

    "ydata-profiling[notebook]>=4.6.5",

    # "auto-sklearn>=0.15.0",
    "featuretools>=1.2.0",
    "h2o>=3.34.0.3",
    "tpot>=0.11.7",

    "statsmodels>=0.13.1",

    "scikit-learn>=1.0",
    "scikit-optimize[plots]>=0.8.1",
    "scikit-plot>=0.3.7",
    "category_encoders>=2.2.2",

    "catboost",
    "darts>=0.24.0",
    "tensorflow>=2.12.0",
    "torch>=1.11.0",
    "xgboost>=1.4.2",
    "xgbfir",

    "pymc3",

    "eli5",
    "lime",
    "shap",

    "nltk",
    "sumy",

    "fastparquet",
    "h5py",
    "svmlight-loader",
    "tables>=3.7.0",

    "kaggle",

    "hdrhistogram",

    "networkx>=3.0",

    "boto3",
    "certifi>=2021.5.30",
    "httpx",
    "requests>=2.26.0",
    "s3fs",
    "smart_open",
]
link = [
    "bokeh",
    "dask-scheduler",
    "dask-ssh",
    "dask-worker",
    "featuretools",
    "jupyter",
    "kaggle",
    "pandas_profiling",
    "ptpython:ml",
    "streamlit",
    "sumy",
    "voila",
    "xgbfir",
]

[virtualenv.mypy]
install = ["mypy"]
link = ["mypy"]

[virtualenv.nbdiff]
install = ["nbdime"]
link = [
    "git-nbdiffdriver",
    "git-nbdifftool",
    "git-nbmergedriver",
    "git-nbmergetool",
    "hg-nbdiff",
    "hg-nbdiffweb",
    "hg-nbmerge",
    "hg-nbmergeweb",
    "nbdiff",
    "nbdiff-web",
    "nbdime",
    "nbmerge",
    "nbmerge-web",
    "nbshow",
]

[virtualenv.neovim]
python = "python3.10"
install = ["jedi", "pynvim", "sphinx"]
post-commands = [["nvim", "+UpdateRemotePlugins", "+quit"]]

[virtualenv.ngxtop]
install = ["ngxtop"]
link = ["ngxtop"]

[virtualenv.pre-commit]
install = ["identify", "pre-commit"]
link = ["identify-cli", "pre-commit"]

[virtualenv.pydocstyle]
install = ["pydocstyle"]
link = ["pydocstyle"]

[virtualenv.pylsp]
install = [
    "pyls-isort",
    "python-lsp-server[all]>=1.7.4",
    "python-lsp-black",
]
link = ["pylsp"]

[virtualenv.pypinfo]
install = ["pypinfo"]
link = ["pypinfo"]

[virtualenv.pyright]
install = ["pyright"]
link = ["pyright", "pyright-langserver"]

[virtualenv.remarshal]
install = ["remarshal"]
link = [
    "json2json",
    "toml2json",
    "yaml2json",
    "json2toml",
    "toml2toml",
    "yaml2toml",
    "json2yaml",
    "toml2yaml",
    "yaml2yaml",
]

[virtualenv.scrapy]
install = ["scrapy"]
link = ["scrapy"]

[virtualenv.ssh-audit]
install = ["ssh-audit"]
link = ["ssh-audit"]

[virtualenv.sphinx]
install-bundle = ["development"]
install = ["recommonmark", "sphinx", "sphinxcontrib.spelling"]
link = [
    "cm2html",
    "cm2latex",
    "cm2man",
    "cm2pseudoxml",
    "cm2xetex",
    "cm2xml",
    "rst2html.py",
    "rst2html5.py",
    "sphinx-apidoc",
    "sphinx-autogen",
    "sphinx-build",
    "sphinx-quickstart",
]
link-module = ["sphinx.ext.intersphinx:intersphinx"]

[virtualenv.steck]
install = ["steck"]
link = ["steck:bpaste", "steck"]

[virtualenv.subunit]
install = ["python-subunit"]
link = [
    "subunit-1to2",
    "subunit-2to1",
    "subunit-filter",
    "subunit-ls",
    "subunit-notify",
    "subunit-output",
    "subunit-stats",
    "subunit-tags",
    "subunit2csv",
    "subunit2disk",
    "subunit2gtk",
    "subunit2junitxml",
    "subunit2pyunit",
    "tap2subunit",
]

[virtualenv.termtosvg]
python = "python3"
install = ["termtosvg"]
link = ["termtosvg"]

[virtualenv.tox]
install = ["tox", "tox-ini-fmt"]
link = ["tox", "tox-ini-fmt"]

[virtualenv.watchdog]
install = ["watchdog[watchmedo]"]
link = ["watchmedo"]

# --- Packaging ---

[virtualenv.build]
install = ["build"]
link = ["pyproject-build"]

[virtualenv.check-manifest]
install = ["check-manifest"]
link = ["check-manifest"]

[virtualenv.hatch]
install = ["hatch"]
link = ["hatch"]

[virtualenv.llm]
install = ["llm"]
link = ["llm"]

[virtualenv.mkpkg]
install = ["mkpkg"]
link = ["mkpkg"]

[virtualenv.nox]
install = ["nox"]
link = ["nox"]

[virtualenv.pex]
install = ["pex"]
link = ["pex"]

[virtualenv.pipenv]
install = ["pipenv"]
link = ["pipenv"]

[virtualenv.poetry]
install = ["poetry"]
link = ["poetry"]

[virtualenv.piptools]
install = ["pip-tools"]
link = ["pip-compile"]

[virtualenv.piptools3]
python = "pypy3"
install = ["pip-tools"]
link = ["pip-compile:pip-compile3"]

[virtualenv.piptools-cpython3]
install = ["pip-tools"]
link = ["pip-compile:pip-compile-cpython3"]

[virtualenv.ruff]
install = ["ruff", "ruff-lsp"]
link = ["ruff", "ruff-lsp"]

[virtualenv.shiv]
install = ["shiv"]
link = ["shiv"]

[virtualenv.twine]
install = ["twine", "keyring"]
link = ["twine", "keyring"]

[virtualenv.wormhole]
install = ["magic-wormhole"]
link = ["wormhole"]

# --- Developing ---

[virtualenv.blog]
requirements = ["${DEVELOPMENT}/til/requirements.txt"]
link = ["pelican", "pelican-quickstart", "pelican-themes"]

[virtualenv.bowtie]
python = "python3.11"
install-bundle = ["development"]
install = ["-e", "${DEVELOPMENT}/bowtie"]
link = ["bowtie"]

[virtualenv.diff]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/diff"]

[virtualenv.regret]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/regret", "twisted[tls]"]

[virtualenv.referencing]
install-bundle = ["development"]
install = ["-e", "${DEVELOPMENT}/referencing"]

[virtualenv.url-py]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/url-py"]

[virtualenv.virtue]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/virtue"]
link = ["virtue"]
