[virtualenv.dev]
install = [
    "betterpath",
    "bpython[urwid]",
    "coverage",
    "ebb-lint",
    "filesystems",
    "flake8",
    "green",
    "hypothesis",
    "inflect",
    "perf",
    "ptpython",
    "pudb",
    "pyrsistent",
    "pytest",
    "pytoml",
    "pyyaml",
    "setuptools",
    "testrepository",
    "treq",
    "twisted[conch,tls]",
    "vmprof",
]
link = [
    "bpython",
    "bpython-urwid",
    "conch",
    "coverage",
    "flake8",
    "green",
    "pip",
    "python",
    "ptpython",
    "pudb",
    "py.test",
    "testr",
    "trial",
    "twist",
    "twistd",
    "vmprofshow",
]

[virtualenv.dev3]
python = "python3"
install = [
    "betterpath",
    "bpython[urwid]",
    "coverage",
    "ebb-lint",
    "filesystems",
    "flake8",
    "green",
    "hypothesis",
    "inflect",
    "perf",
    "ptpython",
    "pudb",
    "pyrsistent",
    "pytest",
    "pytoml",
    "pyyaml",
    "setuptools",
    "testrepository",
    "treq",
    "twisted[conch,tls]",
]

[virtualenv.awscli]
install = ["awscli"]
link = ["aws"]

[virtualenv.diff]
install = [
    "${DEVELOPMENT}/diff",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]

[virtualenv.filesystems]
install = [
    "${DEVELOPMENT}/filesystems",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "testscenarios",
    "twisted",
]

[virtualenv.google]
install = [
    "google-api-python-client",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]

[virtualenv.great]
install = [
    "${DEVELOPMENT}/Great",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]

[virtualenv.gtfo]
install = ["${DEVELOPMENT}/gtfo"]
link = ["gtfo"]

[virtualenv.hg]
python = "python2"
install = ["mercurial"]
link = ["hg"]

[virtualenv.httpie]
install = ["httpie"]
link = ["http"]

[virtualenv.httpstat]
install = ["httpstat"]
link = ["httpstat"]

[virtualenv.jsonschema]
install = ["jsonschema[format]", "mock", "ptpython", "pudb", "twisted"]
link = ["jsonschema"]

[virtualenv.jupyter]
install = [
    "hdrhistogram",
    "jupyter",
    "numpy",
    "octave_kernel",
    "ptpython",
    "requests",
]
link = ["jupyter"]

[virtualenv.minion]
install = [
    "${DEVELOPMENT}/Minion",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]
requirements = ["${DEVELOPMENT}/Minion/test-requirements.txt"]

[virtualenv.mycli]
install = ["mycli"]
link = ["mycli"]

[virtualenv.neovim]
install = ["jedi", "neovim"]

[virtualenv.ngxtop]
install = ["ngxtop"]
link = ["ngxtop"]

[virtualenv.neovim3]
python = "python3"
install = ["jedi", "neovim"]

[virtualenv.pex]
install = ["pex", "requests"]
link = ["pex"]

[virtualenv.shiv]
python = "python3"
install = ["shiv"]
link = ["shiv"]

[virtualenv.pipenv]
install = ["pipenv"]
link = ["pew", "pipenv"]

[virtualenv.pychromecast]
install = ["bpython", "cast", "ptpython", "pychromecast"]
link = ["cast"]

[virtualenv.salt]
install = [
    "salt",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
link = [
    "salt",
    "salt-api",
    "salt-call",
    "salt-cloud",
    "salt-cp",
    "salt-key",
    "salt-master",
    "salt-minion",
    "salt-proxy",
    "salt-run",
    "salt-ssh",
    "salt-syndic",
    "salt-unity",
]

[virtualenv.sphinx]
install = [
    "sphinx",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
link = [
    "rst2html.py",
    "rst2html5.py",
    "sphinx-apidoc",
    "sphinx-autogen",
    "sphinx-build",
]

[virtualenv.tox]
install = ["detox", "tox"]
link = ["detox", "tox"]

[virtualenv.twine]
install = ["twine"]
link = ["twine"]

[virtualenv.yml2json]
install = ["yml2json"]
link = ["yml2json"]

[virtualenv.watchdog]
install = ["watchdog"]
link = ["watchmedo"]
