[virtualenv.dev]
install = [
    "bpython[urwid]",
    "coverage",
    "detox",
    "ebb-lint",
    "filesystems",
    "flake8",
    "green",
    "hypothesis",
    "perf",
    "ptpython",
    "pudb",
    "pyrsistent",
    "pytest",
    "toml",
    "tox",
    "twisted[conch,h2,tls]",
]
link = [
    "bpython",
    "bpython-urwid",
    "coverage",
    "detox",
    "flake8",
    "green",
    "ptpython",
    "pudb",
    "py.test",
    "tox",
    "trial",
    "twist",
]

# [virtualenv.dev3]

[virtualenv.awscli]
install = ["awscli"]
link = ["aws"]

[virtualenv.hg]
install = ["mercurial"]
link = ["hg"]

[virtualenv.httpie]
install = ["httpie"]
link = ["http"]

[virtualenv.httpstat]
install = ["httpstat"]
link = ["httpstat"]

[virtualenv.jsonschema]
install = ["jsonschema[format]", "mock", "ptpython", "pudb", "twisted"]
link = ["jsonschema"]

[virtualenv.jupyter]
install = ["jupyter", "hdrhistogram", "numpy", "ptpython", "requests"]
link = ["jupyter-notebook"]

[virtualenv.mycli]
install = ["mycli"]
link = ["mycli"]

[virtualenv.neovim]
install = ["neovim"]

#
# [virtualenv.neovim3]
# install = ["neovim"]

[virtualenv.pychromecast]
install = ["bpython", "castctrl", "ptpython", "pychromecast"]
link = ["castctrl"]

[virtualenv.twine]
install = ["twine"]
link = ["twine"]

[virtualenv.ansible]
requirements = ["${MAGNETIC_DEVELOPMENT}/Ansible/requirements.txt"]
link = ["ansible", "ansible-playbook"]

[virtualenv.atd_ui]
install = [
    "${MAGNETIC_DEVELOPMENT}/ATD-UI/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/ATD-UI/test-requirements.txt"]
link = ["atd"]

[virtualenv.ca]
install = ["${MAGNETIC_DEVELOPMENT}/ca/"]

[virtualenv.floodgate]
install = [
    "${MAGNETIC_DEVELOPMENT}/Floodgate/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/Floodgate/test-requirements.txt"]
link = ["devpi", "fab", "floodgate"]

[virtualenv.rtb]
requirements = [
    "${MAGNETIC_DEVELOPMENT}/rtb/deploy-requirements.txt",
    "${MAGNETIC_DEVELOPMENT}/rtb/test-requirements.txt",
]
