[virtualenv.dev]
install = [
    "betterpath",
    "bpython[urwid]",
    "coverage",
    "detox",
    "ebb-lint",
    "filesystems",
    "flake8",
    "green",
    "hypothesis",
    "inflect",
    "perf",
    "ptpython",
    "pudb",
    "pyrsistent",
    "pytest",
    "pytoml",
    "pyyaml",
    "setuptools",
    "tox",
    "treq",
    "twisted[conch,tls]",
    "vmprof",
]
link = [
    "bpython",
    "bpython-urwid",
    "conch",
    "coverage",
    "detox",
    "flake8",
    "green",
    "pip",
    "python",
    "ptpython",
    "pudb",
    "py.test",
    "tox",
    "trial",
    "twist",
    "twistd",
    "vmprofshow",
]

# [virtualenv.dev3]

[virtualenv.awscli]
install = ["awscli"]
link = ["aws"]

[virtualenv.diff]
install = [
    "${DEVELOPMENT}/diff",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]

[virtualenv.great]
install = [
    "${DEVELOPMENT}/Great",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]

[virtualenv.gtfo]
install = ["${DEVELOPMENT}/gtfo"]
link = ["gtfo"]

[virtualenv.hg]
install = ["mercurial"]
link = ["hg"]

[virtualenv.httpie]
install = ["httpie"]
link = ["http"]

[virtualenv.httpstat]
install = ["httpstat"]
link = ["httpstat"]

[virtualenv.jsonschema]
install = ["jsonschema[format]", "mock", "ptpython", "pudb", "twisted"]
link = ["jsonschema"]

[virtualenv.jupyter]
install = ["jupyter", "hdrhistogram", "numpy", "ptpython", "requests"]
link = ["jupyter-notebook"]

[virtualenv.minion]
install = [
    "${DEVELOPMENT}/Minion",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]
requirements = ["${DEVELOPMENT}/Minion/test-requirements.txt"]

[virtualenv.mycli]
install = ["mycli"]
link = ["mycli"]

[virtualenv.neovim]
install = ["neovim"]

[virtualenv.ngxtop]
install = ["ngxtop"]
link = ["ngxtop"]

#
# [virtualenv.neovim3]
# install = ["neovim"]

[virtualenv.pex]
install = ["pex"]
link = ["pex"]

[virtualenv.pipenv]
install = ["pipenv"]
link = ["pew", "pipenv"]

[virtualenv.pychromecast]
install = ["bpython", "cast", "ptpython", "pychromecast"]
link = ["cast"]

[virtualenv.sphinx]
install = ["sphinx"]
link = [
    "rst2html.py",
    "rst2html5.py",
    "sphinx-apidoc",
    "sphinx-autogen",
    "sphinx-build",
]

[virtualenv.twine]
install = ["twine"]
link = ["twine"]

[virtualenv.yml2json]
install = ["yml2json"]
link = ["yml2json"]

[virtualenv.watchdog]
install = ["watchdog"]
link = ["watchmedo"]

[virtualenv.ad2d2]
install = [
    "${MAGNETIC_DEVELOPMENT}/ad2d2/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/ad2d2/test-requirements.txt"]

[virtualenv.ds3po]
install = [
    "${MAGNETIC_DEVELOPMENT}/ds3po/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted[tls]",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/ds3po/test-requirements.txt"]

[virtualenv.ads_txt]
install = [
    "${MAGNETIC_DEVELOPMENT}/ads.txt/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/ads.txt/test-requirements.txt"]
link = ["ads.txt"]

[virtualenv.ansible]
requirements = ["${MAGNETIC_DEVELOPMENT}/Ansible/requirements.txt"]
link = ["ansible", "ansible-playbook", "ansible-vault"]

[virtualenv.atd_ui]
install = [
    "${MAGNETIC_DEVELOPMENT}/ATD-UI/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/ATD-UI/test-requirements.txt"]
link = ["atd"]

[virtualenv.ca]
install = ["${MAGNETIC_DEVELOPMENT}/ca/"]

[virtualenv.dw]
install = ["${MAGNETIC_DEVELOPMENT}/DW/"]

[virtualenv.floodgate]
install = [
    "${MAGNETIC_DEVELOPMENT}/Floodgate/",
    "bpython[urwid]",
    "pudb",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/Floodgate/test-requirements.txt"]
link = ["devpi", "fab", "floodgate"]

[virtualenv.kafake]
install = [
    "${MAGNETIC_DEVELOPMENT}/kafake",
    "ptpython",
    "pudb",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/kafake/test-requirements.txt"]

[virtualenv.knox]
install = [
    "${MAGNETIC_DEVELOPMENT}/Knox/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/Knox/test-requirements.txt"]

[virtualenv.magnetic]
install = [
    "${MAGNETIC_DEVELOPMENT}/Magnetic/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/Magnetic/test-requirements.txt"]

[virtualenv.messages]
install = [
    "${MAGNETIC_DEVELOPMENT}/python-messages/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted",
]
requirements = [
    "${MAGNETIC_DEVELOPMENT}/python-messages/test-requirements.txt",
]

[virtualenv.mux]
install = [
    "${MAGNETIC_DEVELOPMENT}/Mux/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/Mux/test-requirements.txt"]

[virtualenv.rtb]
requirements = ["${MAGNETIC_DEVELOPMENT}/rtb/test-requirements.txt"]

[virtualenv.thidwick]
install = [
    "${MAGNETIC_DEVELOPMENT}/Thidwick/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/Thidwick/test-requirements.txt"]

[virtualenv.vast]
install = [
    "${MAGNETIC_DEVELOPMENT}/VAST/",
    "bpython[urwid]",
    "ptpython",
    "pudb",
    "twisted",
]
requirements = ["${MAGNETIC_DEVELOPMENT}/VAST/test-requirements.txt"]
