[bundle]
development = [
    "bpython[urwid]",
    "pipdeptree",
    "ptpython",
    "pudb",
    "q",
    "rich",
    "virtue",
]
core = [
    "coverage",
    "filesystems",
    "glom",
    "hyperlink",
    "hypothesis",
    "inflect",
    "jinja2",
    "pathlib2; python_version<='2.7'",
    "subprocess32; python_version<='2.7'",
    "pyinstrument; platform_python_implementation != 'pypy'",
    "pyperf; python_version>='3'",
    "pyrsistent",
    "pytest",
    "pytest-cov",
    "python-papi; platform_system=='Linux' and platform_machine != 'aarch64'",
    "pytoml",
    "pyyaml",
    "testrepository",
    "treq",
    "twisted[conch,tls]",
]

# --- Development ---

[virtualenv.dev]
python = "pypy"
install-bundle = ["core", "development"]
link = [
    "bpython",
    "bpython-urwid",
    "conch",
    "coverage",
    "glom",
    "pip",
    "python",
    "ptpython",
    "pudb",
    "py.test",
    "testr",
    "trial",
    "twist",
    "twistd",
]
link-module = ["pydoc:pydoc2"]

[virtualenv.dev3]
python = "pypy3"
install-bundle = ["core", "development"]
link = [
    "bpython:bpython3",
    "bpython-urwid:bpython-urwid3",
    "coverage:coverage3",
    "glom:glom3",
    "pip:pip3",
    "python:pypy3",
    "ptpython:ptpypy3",
    "pudb3:pudb3",
    "py.test:py.test3",
    "pyperf:pyperf3",
    "testr:testr3",
    "trial:trial3",
    "twist:twist3",
]
link-module = ["pydoc"]

[virtualenv.dev3-cpython]
python = "python3.9"
install-bundle = ["core", "development"]
install = ["pyinstrument"]
link = [
    "bpython:bpython-cpython3",
    "bpython-urwid:bpython-urwid-cpython3",
    "coverage:coverage-cpython3",
    "glom:glom-cpython3",
    "pip:pip-cpython3",
    "ptpython:ptpython-cpython3",
    "pyinstrument",
    "python:python3",
    "python:cpython3",
    "ptpython:ptpython3",
    "pudb3:pudb-cpython3",
    "py.test:py.test-cpython3",
    "pyperf:pyperf-cpython3",
    "testr:testr-cpython3",
    "trial:trial-cpython3",
    "twist:twist-cpython3",
]
link-module = ["venv"]

[virtualenv.aubio]
python = "python3.9"
install = ["aubio"]
link = ["aubio", "aubiocut"]

[virtualenv.aws]
python = "python3.9"
install-bundle = ["development"]
install = ["awscli", "boto", "boto3", "saws"]
link = ["aws", "saws"]

[virtualenv.bandit]
python = "pypy3"
install = ["bandit"]
link = ["bandit"]

[virtualenv.beets]
python = "python3.9"
install = ["beets", "beautifulsoup4", "pyacoustid", "requests"]
link = ["beet"]

[virtualenv.black]
python = "python3.9"
install = ["black"]
link = ["black"]

[virtualenv.build]
python = "python3.9"
install = ["build"]
link = ["python-build"]

[virtualenv.catt]
python = "python3.9"
install = ["catt"]
link = ["catt"]

[virtualenv.cookiecutter]
python = "python3.9"
install = ["cookiecutter"]
link = ["cookiecutter"]

[virtualenv.check-manifest]
python = "python3.9"
install = ["check-manifest"]
link = ["check-manifest"]

[virtualenv.colortest]
install = ["colortest"]
link = ["colortest"]

[virtualenv.detect-secrets]
install = ["detect-secrets"]
link = ["detect-secrets"]

[virtualenv.doc8]
install = ["doc8", "pygments"]
link = ["doc8"]

[virtualenv.findme]
python = "pypy"
install-bundle = ["development"]
install = ["findme"]
link = ["findme"]

[virtualenv.findme-cpython3]
python = "python3.9"
install-bundle = ["development"]
install = ["findme"]
link = ["findme:findme-cpython3"]

[virtualenv.findme-pypy3]
python = "pypy3"
install-bundle = ["development"]
install = ["findme"]
link = ["findme:findme-pypy3"]

[virtualenv.google]
install-bundle = ["development"]
install = ["google-api-python-client"]

[virtualenv.hg]
install = ["mercurial"]
link = ["hg"]

[virtualenv.httpie]
install = ["httpie"]
link = ["http"]

[virtualenv.httpstat]
install = ["httpstat"]
link = ["httpstat"]

[virtualenv.imaging]
python = "python3.9"
install-bundle = ["development"]
install = [
    "libraw-cffi",
    "pillow",
    "rawkit",
]

[virtualenv.interrogate]
python = "python3.9"
install = ["interrogate"]
link = ["interrogate"]

[virtualenv.isort]
python = "python3.9"
install = ["isort"]
link = ["isort"]

[virtualenv.jsonschema]
install-bundle = ["development"]
install = ["jsonschema[format]", "mock", "twisted"]
link = ["jsonschema"]

[virtualenv.litecli]
python = "python3.9"
install = ["litecli"]
link = ["litecli"]

[virtualenv.math]
python = "python3.9"
install-bundle = ["development"]
install = [
    "mathlibtools",
    "sympy",
]
link = [
    "leanproject",
    "ptpython:math",
]

[virtualenv.ml]
python = "python3.9"
post-commands = [
    [
        "jupyter",
        "labextension",
        "install",
        "@jupyter-widgets/jupyterlab-manager",
        "jupyter-matplotlib",
    ],
    ["jupyter", "lab", "build"],
]
install-bundle = ["core", "development"]
install = [
    "numpy",
    "pandas",

    "dask[complete]",
    "koalas",
    "pyspark",

    "jupyter",
    "jupyterlab",
    "nbdev",
    "nteract_on_jupyter",
    "octave_kernel",

    "jupyter-lsp",
    "python-language-server[all]",

    "ipympl",
    "matplotlib",
    "altair",
    "altair_saver",
    "git+https://github.com/altair-viz/altair_pandas",

    "bokeh",
    "graphviz",
    "plotly",
    "plotnine",
    "seaborn",
    "yellowbrick",

    "streamlit",
    "voila",

    "pandas-profiling[notebook]",

    "auto-sklearn",
    "featuretools",
    "h2o",
    "tpot",

    "scikit-learn",
    "scikit-optimize[plots]",
    "scikit-plot",
    "category_encoders",

    "fbprophet",
    "tensorflow",
    "torch",
    "xgboost",
    "xgbfir",

    "pymc3",

    "eli5",
    "lime",
    "shap",

    "nltk",
    "sumy",

    "fastparquet",
    "h5py",
    "svmlight-loader",
    "tables",

    "kaggle",

    "hdrhistogram",

    "networkx",

    "boto3",
    "requests",
    "s3fs",
    "smart_open",
]
link = [
    "bokeh",
    "dask-scheduler",
    "dask-ssh",
    "dask-worker",
    "featuretools",
    "jupyter",
    "kaggle",
    "pandas_profiling",
    "ptpython:ml",
    "streamlit",
    "sumy",
    "voila",
    "xgbfir",
]

[virtualenv.mkpkg]
install = ["mkpkg"]
link = ["mkpkg"]

[virtualenv.mypy]
python = "python3.9"
install = ["mypy"]
link = ["mypy"]

[virtualenv.nbdiff]
python = "python3.9"
install = ["nbdime"]
link = [
    "git-nbdiffdriver",
    "git-nbdifftool",
    "git-nbmergedriver",
    "git-nbmergetool",
    "hg-nbdiff",
    "hg-nbdiffweb",
    "hg-nbmerge",
    "hg-nbmergeweb",
    "nbdiff",
    "nbdiff-web",
    "nbdime",
    "nbmerge",
    "nbmerge-web",
    "nbshow",
]

[virtualenv.neovim]
python = "pypy"
install = ["pynvim", "jedi"]

[virtualenv.neovim3]
python = "python3.9"
install = ["pynvim", "jedi", "python-language-server[all]", "sphinx"]
post-commands = [["nvim", "+UpdateRemotePlugins", "+quit"]]
link = ["pyls"]

[virtualenv.ngxtop]
install = ["ngxtop"]
link = ["ngxtop"]

[virtualenv.nox]
python = "python3.9"
install = ["nox"]
link = ["nox"]

[virtualenv.pex]
install = ["pex"]
link = ["pex"]

[virtualenv.pipenv]
python = "python3.9"
install = ["pipenv"]
link = ["pipenv"]

[virtualenv.poetry]
install = ["poetry"]
link = ["poetry"]

[virtualenv.piptools]
install = ["pip-tools"]
link = ["pip-compile"]

[virtualenv.piptools3]
python = "pypy3"
install = ["pip-tools"]
link = ["pip-compile:pip-compile3"]

[virtualenv.piptools-cpython3]
python = "python3.9"
install = ["pip-tools"]
link = ["pip-compile:pip-compile-cpython3"]

[virtualenv.pre-commit]
python = "python3.9"
install = ["pre-commit"]
link = ["pre-commit"]

[virtualenv.pydocstyle]
python = "python3.9"
install = ["pydocstyle"]
link = ["pydocstyle"]

[virtualenv.pypinfo]
python = "python3.9"
install = ["pypinfo"]
link = ["pypinfo"]

[virtualenv.remarshal]
install = ["remarshal"]
link = [
    "json2json",
    "toml2json",
    "yaml2json",
    "json2toml",
    "toml2toml",
    "yaml2toml",
    "json2yaml",
    "toml2yaml",
    "yaml2yaml",
]

[virtualenv.scrapy]
python = "python3.9"
install = ["scrapy"]
link = ["scrapy"]

[virtualenv.ssh-audit]
python = "python3.9"
install = ["ssh-audit"]
link = ["ssh-audit"]

[virtualenv.shiv]
python = "python3.9"
install = ["shiv"]
link = ["shiv"]

[virtualenv.sphinx]
python = "python3.9"
install-bundle = ["development"]
install = ["recommonmark", "sphinx", "sphinxcontrib.spelling"]
link = [
    "cm2html",
    "cm2latex",
    "cm2man",
    "cm2pseudoxml",
    "cm2xetex",
    "cm2xml",
    "rst2html.py",
    "rst2html5.py",
    "sphinx-apidoc",
    "sphinx-autogen",
    "sphinx-build",
    "sphinx-quickstart",
]
link-module = ["sphinx.ext.intersphinx:intersphinx"]

[virtualenv.steck]
python = "python3.9"
install = ["steck"]
link = ["steck:bpaste", "steck"]

[virtualenv.style]
python = "pypy"
install = ["flake8"]
link = ["flake8"]

[virtualenv.style3]
python = "python3.9"
install = ["flake8"]
link = ["flake8:flake83"]

[virtualenv.subunit]
install = ["python-subunit"]
link = [
    "subunit-1to2",
    "subunit-2to1",
    "subunit-filter",
    "subunit-ls",
    "subunit-notify",
    "subunit-output",
    "subunit-stats",
    "subunit-tags",
    "subunit2csv",
    "subunit2disk",
    "subunit2gtk",
    "subunit2junitxml",
    "subunit2pyunit",
    "tap2subunit",
]

[virtualenv.termtosvg]
python = "python3"
install = ["termtosvg"]
link = ["termtosvg"]

[virtualenv.tox]
python = "python3.9"
install = ["tox", "tox-ini-fmt"]
link = ["tox", "tox-ini-fmt"]

[virtualenv.twine]
install = ["twine", "keyring"]
link = ["twine", "keyring"]

[virtualenv.watchdog]
install = ["watchdog[watchmedo]"]
link = ["watchmedo"]

[virtualenv.youtube-dl]
install = ["youtube-dl"]
link = ["youtube-dl"]

# --- Developing ---

[virtualenv.blog]
python = "python3.9"
requirements = [
    "${DEVELOPMENT}/julian.github.io/requirements.txt",
    "${DEVELOPMENT}/til/requirements.txt",
]
link = ["invoke", "pelican", "pelican-quickstart", "pelican-themes"]

[virtualenv.diff]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/diff", "twisted[tls]"]

[virtualenv.filesystems]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/filesystems", "testscenarios", "twisted"]

[virtualenv.great]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/Great", "twisted[tls]"]
requirements = [
    "${DEVELOPMENT}/Great/test-requirements.txt",
    "${DEVELOPMENT}/Great/automanual/requirements.txt",
]

[virtualenv.regret]
python = "python3.9"
install-bundle = ["development"]
install = ["${DEVELOPMENT}/regret", "twisted[tls]"]

[virtualenv.virtue]
install-bundle = ["development"]
install = ["${DEVELOPMENT}/virtue"]
link = ["virtue"]
