#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
tags_tmp="${dir}/ctags.$$.tmp"
trap "rm -f ${tags_tmp}" EXIT
git ls-files | ctags -L - --tag-relative -f"${tags_tmp}" --languages=-javascript,sql
mv "$tags_tmp" "${dir}/tags"
