#! /bin/zsh

export DE=qtile


[[ -f $XDG_CONFIG_HOME/X11/Xresources ]] && xrdb -merge $XDG_CONFIG_HOME/X11/Xresources 
[[ -f $XDG_CONFIG_HOME/X11/Xresources.colorscheme ]] && xrdb -merge $XDG_CONFIG_HOME/X11/Xresources.colorscheme

[[ -x /usr/bin/qiv ]] && /usr/bin/qiv -n -z ~/.wallpaper
[[ -x /usr/bin/xscreensaver ]] && /usr/bin/xscreensaver -no-splash &

xsetroot -cursor_name left_ptr &


# Caps Lock: Super
# Control_L: Meta
# Windows: Alt
# Alt_L: Control
# Alt_R: Control
# Menu: Compose
# Control_R: Hyper (Not yet implemented)

setxkbmap \
    -option caps:super \
    -option altwin:ctrl_alt_win
    -option ctrl:lctrl_meta \
    -option compose:menu


if [[ $1 == "gnome" ]]
then
    DE=gnome-session
fi


exec ck-launch-session $DE
