name: CI

on:
  push:
  schedule:
    # Daily at 8:11
    - cron: "11 8 * * *"

concurrency:
  group: "dotfiles"
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        if: runner.os == 'macOS'
      - name: Build darwin configuration
        run: nix build --print-build-logs '.#darwinConfigurations.Airm.system'
        if: runner.os == 'macOS'
      - name: Upload flake.lock
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: runner.os == 'macOS'
        with:
          name: flake-lock
          path: flake.lock
      - name: Install packages
        run: sudo apt-get install -y zsh
        if: runner.os == 'Linux'
      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: false
      - name: Bootstrap
        run: uv run ./install
      - name: Converge venvs
        run: uvx venvs converge
        env:
          DEVELOPMENT: ${{ runner.temp }}/Development
